# Generated by Django 5.2.3 on 2025-07-21 14:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250706_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ai_checked_status',
            field=models.CharField(choices=[('ai_checked_true', 'Проверено'), ('ai_checked_in_progress', 'Проверяется'), ('ai_checked_false', 'Не проверено')], default='ai_checked_false', max_length=50, verbose_name='Статус проверки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 7, 21))], verbose_name='Дата записи'),
        ),
    ]
