# Generated by Django 5.2.3 on 2025-07-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review_ai_checked_status_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ai_checked_status',
            field=models.CharField(choices=[('ai_checked_true', 'Проверено'), ('ai_cancelled', 'Отменено'), ('ai_checked_in_progress', 'Проверяется'), ('ai_checked_false', 'Не проверено')], default='ai_checked_false', max_length=50, verbose_name='Статус проверки'),
        ),
    ]
