# Generated by Django 5.2.3 on 2025-07-22 16:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_review_ai_checked_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'permissions': [('can_moderate', 'Может модерировать отзывы')], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 7, 22))], verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ai_checked_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved by AI'), ('rejected', 'Rejected by AI'), ('manual', 'Manual Review Required')], default='pending', max_length=20, verbose_name='AI Check Status'),
        ),
    ]
